# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{chronic18n}
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcos Piccinini"]
  s.date = %q{2010-06-21}
  s.description = %q{One 'way' to i18n chronic}
  s.email = %q{x@nofxx.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "chronic18n.gemspec",
     "lib/chronic18n.rb",
     "lib/chronic18n/dics/es.yml",
     "lib/chronic18n/dics/es_regex.yml",
     "lib/chronic18n/dics/it.yml",
     "lib/chronic18n/dics/it_regex.yml",
     "lib/chronic18n/dics/pt.yml",
     "lib/chronic18n/dics/pt_regex.yml",
     "lib/chronic18n/translator.rb",
     "spec/chronic18n/en_spec.rb",
     "spec/chronic18n/es_spec.rb",
     "spec/chronic18n/it_spec.rb",
     "spec/chronic18n/pt_spec.rb",
     "spec/chronic18n_spec.rb",
     "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/nofxx/chronic18n}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{i18n chronic}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/chronic18n/es_spec.rb",
     "spec/chronic18n/en_spec.rb",
     "spec/chronic18n/pt_spec.rb",
     "spec/chronic18n/it_spec.rb",
     "spec/chronic18n_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<chronic>, [">= 0.2.3"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
    else
      s.add_dependency(%q<chronic>, [">= 0.2.3"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
    end
  else
    s.add_dependency(%q<chronic>, [">= 0.2.3"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
  end
end

