# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "chronic18n"
  s.version = "0.0.4"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcos Piccinini"]
  s.date = "2012-01-05"
  s.description = "One 'way' to i18n chronic"
  s.email = "x@nofxx.com"
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "chronic18n.gemspec",
    "lib/chronic18n.rb",
    "lib/chronic18n/dics/es.yml",
    "lib/chronic18n/dics/es_regex.yml",
    "lib/chronic18n/dics/it.yml",
    "lib/chronic18n/dics/it_regex.yml",
    "lib/chronic18n/dics/pt.yml",
    "lib/chronic18n/dics/pt_regex.yml",
    "lib/chronic18n/translator.rb",
    "spec/chronic18n/en_spec.rb",
    "spec/chronic18n/es_spec.rb",
    "spec/chronic18n/it_spec.rb",
    "spec/chronic18n/pt_spec.rb",
    "spec/chronic18n_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/nofxx/chronic18n"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.12"
  s.summary = "i18n chronic"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0')
      # s.add_runtime_dependency(%q<chronic>, [">= 0.2.3"])
      s.add_development_dependency('rspec', ['>= 1.2.9'])
    else
      # s.add_dependency(%q<chronic>, [">= 0.2.3"])
      s.add_dependency('rspec', ['>= 1.2.9'])
    end
  else
    # s.add_dependency(%q<chronic>, [">= 0.2.3"])
    s.add_dependency('rspec', ['>= 1.2.9'])
  end
end

