version: 2

jobs:
  build:
    docker:
      - image: jobseeker/docker-library:ruby-2.4-ci-bionic
        auth:
          username: $DOCKER_USER
          password: $DOCKER_PASS
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
            - v2-gem-cache-{{ arch }}-{{ .Branch }}
            - v2-gem-cache
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: v2-gem-cache-{{ arch }}-{{ .Branch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: mkdir /reports
      - run: bundle exec rspec -f progress -f RspecJunitFormatter -o /reports/rspec.xml
      - store_test_results:
          path: /reports

workflows:
  version: 2
  rspec:
    jobs:
      - build
